### ISSUE TITLE
数据解码

### ISSUE THREAD

**Issue by ChinaGISboyYang** [wendy512/iec104#3]
您好，数据帧解码可以吗？

**Comment by wendy512** [comment]
请具体描述你的问题，本身就支持数据帧解码

**Comment by ChinaGISboyYang** [comment]
对于归一化值，好像解析有点问题。
另外想问下，您有计划对102协议golang做支持么

**Comment by wendy512** [comment]
解析哪里有问题，具体指出，我们好持续改进。
如果您有好的解决方案请直接提起PR，102协议暂时没有支持的计划。
